/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux lcgapp-slc6-x86-64-25.cern.ch 2.6.32-573.18.1.el6.x86_64 #1 SMP Wed Feb 10 14:02:50 CET 2016 x86_64 x86_64 x86_64 GNU/Linux"
#define CXX "g++"
#define COMPILER "/afs/cern.ch/sw/lcg/contrib/gcc/4.8/x86_64-slc6/bin/g++"
#define COMPILERVERS "gcc484"
#define MAKESHAREDLIB  "cd $BuildDir ; g++ -c $Opt -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations $IncludePath $SourceFiles ; g++ $ObjectFiles -shared  $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; g++ -c  -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations $IncludePath $SourceFiles; g++ $ObjectFiles  -o $ExeName $LinkedLibs -lm -ldl -lpthread -rdynamic"
#define CXXOPT "-O2 -DNDEBUG"
#define CXXDEBUG "-g  -fno-reorder-blocks -fno-schedule-insns -fno-inline"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o"
#define SOEXT "so"
