# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

# The macro below is expanded when 'realpath' is not built-in.
# Built-in 'realpath' is available on GNU Make 3.81.
realpath = $(shell cd $(1); pwd)

ROOT_SRCDIR    := $(call realpath, /app/root)
ROOT_OBJDIR    := $(call realpath, /app/root)

ifndef ROOT_SRCDIR
$(error Error determining ROOT_SRCDIR)
endif
ifndef ROOT_OBJDIR
$(error Error determining ROOT_OBJDIR)
endif

# The macro below strips off the source dir path to make a relative path name
stripsrc = $(subst $(ROOT_SRCDIR)/,,$(1))

ARCH           := linuxx8664gcc
HOST           := 

USECONFIG      := FALSE
MKLIBOPTIONS   := 

EXTRA_CFLAGS   := -Iinclude 
EXTRA_CXXFLAGS := -Iinclude 
EXTRA_LDFLAGS  := 
WINRTDEBUG     := no

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=    

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man/man1
DATADIR        := $(ROOTSYS)
ELISPDIR       := $(ROOTSYS)/build/misc
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := .
ICONPATH       := $(ROOTSYS)/icons
CINTINCDIR     := $(ROOTSYS)/cint
DOCDIR         := $(ROOTSYS)
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/build/misc

BUILDX11       := yes
X11LIBDIR      := 
XPMLIBDIR      := -L/lib64
XPMLIB         := -lXpm
XFTLIB         := yes

EXCEPTIONS     := yes
EXPLICITLINK   := no

ENABLETHREAD   := yes
OSTHREADFLAG   := -pthread
OSTHREADLIBDIR := 
OSTHREADLIB    := -pthread

BUILTINFREETYPE:= no

BUILTINPCRE    := yes

BUILTINZLIB    := no
ZLIBLIBDIR     := -L/lib64
ZLIBCLILIB     := -lz
ZLIBINCDIR     := $(filter-out /usr/include, /usr/include)

BUILDGL        := no
OPENGLLIBDIR   := 
OPENGLULIB     := 
OPENGLLIB      := 
OPENGLINCDIR   := $(filter-out /usr/include, )

BUILDLDAP      := no
LDAPLIBDIR     := 
LDAPCLILIB     := 
LDAPINCDIR     := $(filter-out /usr/include, )

BUILDMYSQL     := no
MYSQLLIBDIR    := 
MYSQLCLILIB    := 
MYSQLINCDIR    := $(filter-out /usr/include, )

BUILDORACLE    := no
ORACLELIBDIR   := 
ORACLECLILIB   :=  
ORACLEINCDIR   := $(filter-out /usr/include, )

BUILDPGSQL     := no
PGSQLLIBDIR    := 
PGSQLCLILIB    := 
PGSQLINCDIR    := $(filter-out /usr/include, )

BUILDSAPDB     := no
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := no
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDQT        := no
BUILDQTGSI     := no
QTLIBDIR       := 
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, )
QTVERS	       := 
QTMOCEXE       := 

BUILDRFIO      := no
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := no
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, )
CASTORCFLAGS   := 

BUILDDCAP      := no
DCAPLIBDIR     := 
DCAPLIB        := 
DCAPINCDIR     := $(filter-out /usr/include, )

BUILDFTGL      := no
FTGLLIBDIR     := 
FTGLLIBS       := 
FTGLINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := no
GLEWLIBDIR     := 
GLEWLIBS       := 
GLEWINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := no
GFALLIBDIR     := 
GFALCLILIB     := 
GFALINCDIR     := $(filter-out /usr/include, )

BUILDGLITE     := no
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := yes

BUILDBONJOUR   := no
DNSSDLIBDIR    := 
DNSSDLIB       := 
DNSSDINCDIR    := $(filter-out /usr/include, )
BONJOURCPPFLAGS := 

BUILDCHIRP     := no
CHIRPLIBDIR    := 
CHIRPCLILIB    := 
CHIRPINCDIR    := $(filter-out /usr/include, )

BUILDHDFS      := no
HDFSLIBDIR     := 
HDFSCLILIB     := 
HDFSINCDIR     := $(filter-out /usr/include, )
JNIINCDIR      := $(filter-out /usr/include, ) $(filter-out /usr/include, /linux)
JVMCLILIB      := 
JVMLIBDIR      := 

BUILDALIEN     := no
ALIENLIBDIR    := 
ALIENCLILIB    := 
ALIENINCDIR    := $(filter-out /usr/include, )

BUILDASIMAGE   := yes
BUILTINASIMAGE := yes
ASEXTRALIB     :=  -lpng -lz
ASEXTRALIBDIR  :=  -L/lib64 -L/lib64
ASJPEGINCDIR   := $(filter-out /usr/include, )
ASPNGINCDIR    := $(filter-out /usr/include, /usr/include)
ASTIFFINCDIR   := $(filter-out /usr/include, )
ASGIFINCDIR    := $(filter-out /usr/include, )
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := no
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := 
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := no
FPYTHIA8INCDIR   := 
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := 

BUILDFFTW3     := no
FFTW3LIBDIR    := 
FFTW3LIB       := 
FFTW3INCDIR    := $(filter-out /usr/include, )

BUILDFITSIO    := no
CFITSIOLIBDIR  := 
CFITSIOLIB     := 
CFITSIOINCDIR  := $(filter-out /usr/include, )

BUILDGVIZ      := no
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := no
PYTHONLIBDIR   := 
PYTHONLIB      := 
PYTHONINCDIR   := $(filter-out /usr/include, )
PYTHONLIBFLAGS := 

BUILDRUBY      := no
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := no
XMLLIBDIR      := 
XMLCLILIB      := 
XMLINCDIR      := $(filter-out /usr/include, )

BUILDXRD       := yes
XRDINCDIR      := 
XRDLIBDIR      := 
XRDADDOPTS     := 
EXTRA_XRDFLAGS := -DUSENEWHDRS
XRDVERSION     := 20100913

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

ALLOCLIB       := 
ALLOCLIBDIR    := 

BUILDKRB5      := no
KRB5LIB        := 
KRB5LIBDIR     := 
KRB5INCDIR     := $(filter-out /usr/include, )
KRB5INIT       := 

COMERRLIB      := 
COMERRLIBDIR   := 

RESOLVLIB      := 

CRYPTOLIB      := 
CRYPTOLIBDIR   := 

BUILDGLOBUS    := no
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )
BUILDXRDGSI    := yes

BUILDMONALISA  := no
MONALISALIBDIR := 
MONALISACLILIB := 
MONALISAINCDIR := $(filter-out /usr/include, )

SSLLIB         := 
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, )
SSLSHARED      := yes

SHADOWFLAGS    := -DR__SHADOWPW 
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDGENVECTOR := yes

BUILDMATHMORE  := no
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := 
GSLVERSION     := 

BUILDCLING     := no

BUILDCINTEX    := yes

BUILDREFLEX    := yes

BUILDROOFIT    := 

BUILDMINUIT2   := 

BUILDUNURAN    := 

BUILDGDML      := 

BUILDTABLE     := 

BUILDTMVA      := yes

BUILDCLARENS   := no
CLARENSINC     := $(filter-out -I/usr/include, )
CLARENSLIBS    := 

BUILDPEAC      := no

CURSESINCDIR   := $(filter-out -I/usr/include, -I)
CURSESLIBDIR   := 
CURSESHDR      := 
CURSESLIB      := 
BUILDEDITLINE  := no

CPPUNIT        := 
GCCXML         := 

ROOTDICTTYPE   := cint

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p
RSYNC          := rsync -au

ROOTDRPMREL    := 1
